import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';

const FIREBASE_CONFIG={apiKey:'AIzaSyCR6nPQIG9GLgbiLCVCZOc785j8BMicwQA',authDomain:'island-journey-rgb.firebaseapp.com',projectId:'island-journey-rgb',messagingSenderId:'840035091382',storageBucket:'island-journey-rgb.firebasestorage.app'};
const ADMIN_EMAIL='info@rgb-workshop.com',ENDPOINT='https://firestore.googleapis.com/v1/projects/island-journey-rgb/databases/(default)/documents/miniGames/jigsawPuzzle';
const auth=getAuth(initializeApp(FIREBASE_CONFIG)),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s);
const textLabels={title:'遊戲名稱',eyebrow:'英文眉題',instructions:'玩法說明',previewLabel:'提示圖標籤',shuffleButton:'重新排列按鈕',statusInitial:'初始提示',statusSelected:'選中一塊後提示',statusCancelled:'取消選擇提示',statusContinue:'交換後提示',statusShuffled:'重新排列提示',statusComplete:'完成關卡提示',levelPrefix:'關卡數字前文字',levelSuffix:'關卡數字後文字',scoreUnit:'分數單位',levelCompleteEyebrow:'過關英文眉題',levelCompleteTitle:'過關標題（可用 {level}）',levelCompleteText:'過關說明',nextButton:'下一關按鈕',finishEyebrow:'全數完成英文眉題',finishTitle:'全數完成標題',finishText:'全數完成說明',finishButton:'帶走分數按鈕（可用 {score}）',sentButton:'分數送出後文字'};
let config;

async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}
async function loadPublished(){const response=await fetch(ENDPOINT,{cache:'no-store'});if(response.status===404)return fallback();if(!response.ok)throw new Error(`讀取失敗 (${response.status})`);const data=await response.json(),payload=data.fields?.payload?.stringValue;return payload?JSON.parse(payload):fallback()}
function setMessage(target,text,error=false){target.textContent=text;target.classList.toggle('error',error)}
function renderTexts(){const box=$('#textFields');box.innerHTML='';Object.entries(textLabels).forEach(([key,label])=>{const field=document.createElement('label');field.textContent=label;const input=document.createElement(key.includes('Text')||key==='instructions'?'textarea':'input');input.dataset.textKey=key;input.value=config.texts[key]||'';field.appendChild(input);box.appendChild(field)})}
function levelCard(level,index){const card=document.createElement('article');card.className='level-card';card.dataset.index=index;card.innerHTML=`<b>第 ${index+1} 關</b><div class="level-grid"><label>關卡名稱<input data-key="name" value="${escapeHtml(level.name)}" required></label><label>16:9 圖片 URL<input data-key="image" value="${escapeHtml(level.image)}" required></label><label>分數<input data-key="score" type="number" min="0" step="1" value="${Number(level.score)||0}" required></label><label>難度<select data-key="difficulty"><option value="easy">容易 3×3</option><option value="medium">中等 4×4</option><option value="hard">困難 5×5</option></select></label></div><div class="level-actions"><button type="button" class="danger remove">刪除此關</button></div>`;card.querySelector('select').value=level.difficulty||'easy';card.querySelector('.remove').onclick=()=>{if(config.levels.length<=1)return setMessage($('#saveMessage'),'最少需要一關。',true);readForm();config.levels.splice(index,1);renderLevels()};return card}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderLevels(){const box=$('#levels');box.innerHTML='';config.levels.forEach((level,index)=>box.appendChild(levelCard(level,index)))}
function render(){renderTexts();renderLevels()}
function readForm(){document.querySelectorAll('[data-text-key]').forEach(input=>config.texts[input.dataset.textKey]=input.value.trim());config.levels=[...document.querySelectorAll('.level-card')].map(card=>({name:card.querySelector('[data-key=name]').value.trim(),image:card.querySelector('[data-key=image]').value.trim(),score:Number(card.querySelector('[data-key=score]').value)||0,difficulty:card.querySelector('[data-key=difficulty]').value}))}
async function reload(){setMessage($('#saveMessage'),'正在載入…');try{config=await loadPublished();render();setMessage($('#saveMessage'),'已載入目前公開設定。')}catch(error){setMessage($('#saveMessage'),error.message,true)}}
async function publish(event){event.preventDefault();readForm();if(!config.levels.length)return setMessage($('#saveMessage'),'最少需要一關。',true);setMessage($('#saveMessage'),'正在發佈…');try{const token=await auth.currentUser.getIdToken(true),response=await fetch(ENDPOINT,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(config)},updatedAt:{timestampValue:new Date().toISOString()}}})});if(!response.ok){const detail=await response.text();throw new Error(`發佈失敗 (${response.status}) ${detail}`)}setMessage($('#saveMessage'),'發佈成功！前台重新開啟後會使用新設定。')}catch(error){setMessage($('#saveMessage'),error.message,true)}}

$('#loginButton').onclick=async()=>{setMessage($('#loginMessage'),'正在開啟 Google 登入…');try{await signInWithPopup(auth,provider)}catch(error){setMessage($('#loginMessage'),`登入失敗：${error.message}`,true)}};
$('#logout').onclick=()=>signOut(auth);$('#reload').onclick=reload;$('#editor').onsubmit=publish;
$('#addLevel').onclick=()=>{readForm();const n=config.levels.length+1;config.levels.push({name:`第${n}關`,image:'assets/level-1.svg',score:200,difficulty:'easy'});renderLevels()};
onAuthStateChanged(auth,async user=>{const allowed=user?.email?.toLowerCase()===ADMIN_EMAIL&&user.emailVerified;if(user&&!allowed){await signOut(auth);setMessage($('#loginMessage'),`此帳戶沒有管理權限：${user.email}`,true);return}$('#login').hidden=!!allowed;$('#editor').hidden=!allowed;$('#logout').hidden=!allowed;if(allowed){$('#userEmail').textContent=user.email;await reload()}});
