import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
const FIREBASE_CONFIG={apiKey:'AIzaSyCR6nPQIG9GLgbiLCVCZOc785j8BMicwQA',authDomain:'island-journey-rgb.firebaseapp.com',projectId:'island-journey-rgb',messagingSenderId:'840035091382',storageBucket:'island-journey-rgb.firebasestorage.app'};
const ADMIN_EMAIL='info@rgb-workshop.com',ROOT='https://firestore.googleapis.com/v1/projects/island-journey-rgb/databases/(default)/documents/miniGames/jigsawPuzzle',VERSIONS=`${ROOT}/versions`;
const auth=getAuth(initializeApp(FIREBASE_CONFIG)),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s);
const textLabels={title:'遊戲名稱',eyebrow:'英文眉題',instructions:'玩法說明',previewLabel:'提示圖標籤',shuffleButton:'重新排列按鈕',statusInitial:'初始提示',statusSelected:'選中一塊後提示',statusCancelled:'取消選擇提示',statusContinue:'交換後提示',statusShuffled:'重新排列提示',statusComplete:'完成關卡提示',levelPrefix:'關卡數字前文字',levelSuffix:'關卡數字後文字',scoreUnit:'分數單位',levelCompleteEyebrow:'過關英文眉題',levelCompleteTitle:'過關標題（可用 {level}）',levelCompleteText:'過關說明',nextButton:'下一關按鈕',finishEyebrow:'全數完成英文眉題',finishTitle:'全數完成標題',finishText:'全數完成說明',finishButton:'帶走分數按鈕（可用 {score}）',sentButton:'分數送出後文字'};
let config,currentId='',versions=[];
async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}
function endpoint(id=currentId){return id?`${VERSIONS}/${encodeURIComponent(id)}`:ROOT}
function payloadFrom(document){const value=document?.fields?.payload?.stringValue;return value?JSON.parse(value):null}
async function loadDocument(id=currentId){const response=await fetch(endpoint(id),{cache:'no-store'});if(response.status===404)return fallback();if(!response.ok)throw new Error(`讀取失敗 (${response.status})`);return payloadFrom(await response.json())||fallback()}
async function loadVersions(){const response=await fetch(`${VERSIONS}?pageSize=100`,{cache:'no-store'});if(response.status===404){versions=[];return}if(!response.ok)throw new Error(`版本清單讀取失敗 (${response.status})`);const data=await response.json();versions=(data.documents||[]).map(document=>{const fields=document.fields||{},id=document.name.split('/').pop();return{id,name:fields.displayName?.stringValue||id}}).sort((a,b)=>a.name.localeCompare(b.name,'zh-HK'))}
function setMessage(target,text,error=false){target.textContent=text;target.classList.toggle('error',error)}
function versionUrl(id=currentId){const url=new URL('./',location.href);url.pathname=url.pathname.replace(/admin\.html$/,'');if(id)url.searchParams.set('version',id);return url.href}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function renderVersionControls(){const select=$('#versionSelect');select.innerHTML='<option value="">預設版本</option>'+versions.map(v=>`<option value="${escapeHtml(v.id)}">${escapeHtml(v.name)} (${escapeHtml(v.id)})</option>`).join('');select.value=currentId;const meta=versions.find(v=>v.id===currentId);$('#versionName').value=currentId?(meta?.name||currentId):'預設版本';$('#versionName').disabled=!currentId;$('#deleteVersion').disabled=!currentId;$('#versionLink').textContent=versionUrl()}
function renderTexts(){const box=$('#textFields');box.innerHTML='';Object.entries(textLabels).forEach(([key,label])=>{const field=document.createElement('label');field.textContent=label;const input=document.createElement(key.includes('Text')||key==='instructions'?'textarea':'input');input.dataset.textKey=key;input.value=config.texts[key]||'';field.appendChild(input);box.appendChild(field)})}
function levelCard(level,index){const card=document.createElement('article');card.className='level-card';card.dataset.index=index;card.innerHTML=`<b>第 ${index+1} 關</b><div class="level-grid"><label>關卡名稱<input data-key="name" value="${escapeHtml(level.name)}" required></label><label>16:9 圖片 URL<input data-key="image" value="${escapeHtml(level.image)}" required></label><label>分數<input data-key="score" type="number" min="0" step="1" value="${Number(level.score)||0}" required></label><label>難度<select data-key="difficulty"><option value="easy">容易 3×3</option><option value="medium">中等 4×4</option><option value="hard">困難 5×5</option></select></label></div><div class="level-actions"><button type="button" class="danger remove">刪除此關</button></div>`;card.querySelector('select').value=level.difficulty||'easy';card.querySelector('.remove').onclick=()=>{if(config.levels.length<=1)return setMessage($('#saveMessage'),'最少需要一關。',true);readForm();config.levels.splice(index,1);renderLevels()};return card}
function renderLevels(){const box=$('#levels');box.innerHTML='';config.levels.forEach((level,index)=>box.appendChild(levelCard(level,index)))}
function render(){renderVersionControls();renderTexts();renderLevels()}
function readForm(){document.querySelectorAll('[data-text-key]').forEach(input=>config.texts[input.dataset.textKey]=input.value.trim());config.levels=[...document.querySelectorAll('.level-card')].map(card=>({name:card.querySelector('[data-key=name]').value.trim(),image:card.querySelector('[data-key=image]').value.trim(),score:Number(card.querySelector('[data-key=score]').value)||0,difficulty:card.querySelector('[data-key=difficulty]').value}))}
function slugify(value){return String(value).trim().toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)}
async function token(){return auth.currentUser.getIdToken(true)}
async function reload(){setMessage($('#saveMessage'),'正在載入…');try{await loadVersions();config=await loadDocument();render();setMessage($('#saveMessage'),'已載入目前版本。')}catch(error){setMessage($('#saveMessage'),error.message,true)}}
async function writeVersion(id,name,data){const response=await fetch(endpoint(id),{method:'PATCH',headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(data)},displayName:{stringValue:name},updatedAt:{timestampValue:new Date().toISOString()}}})});if(!response.ok)throw new Error(`發佈失敗 (${response.status}) ${await response.text()}`)}
async function publish(event){event.preventDefault();readForm();if(!config.levels.length)return setMessage($('#saveMessage'),'最少需要一關。',true);setMessage($('#saveMessage'),'正在發佈…');try{if(currentId){const name=$('#versionName').value.trim()||currentId;await writeVersion(currentId,name,config)}else{const response=await fetch(ROOT,{method:'PATCH',headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(config)},updatedAt:{timestampValue:new Date().toISOString()}}})});if(!response.ok)throw new Error(`發佈失敗 (${response.status}) ${await response.text()}`)}await loadVersions();renderVersionControls();setMessage($('#saveMessage'),`發佈成功！前台網址：${versionUrl()}`)}catch(error){setMessage($('#saveMessage'),error.message,true)}}
async function createVersion(copyCurrent){readForm();const name=prompt(copyCurrent?'新版本名稱（會複製目前設定）':'新版本名稱');if(!name)return;const suggested=slugify(name)||`version-${Date.now().toString(36)}`,id=prompt('版本代號（只可使用英文小寫、數字及連字號）',suggested);if(!id)return;if(!/^[a-z0-9-]{1,40}$/.test(id))return setMessage($('#saveMessage'),'版本代號格式不正確。',true);if(versions.some(v=>v.id===id))return setMessage($('#saveMessage'),'此版本代號已存在。',true);setMessage($('#saveMessage'),'正在建立版本…');try{await writeVersion(id,name,copyCurrent?structuredClone(config):await fallback());currentId=id;await reload();setMessage($('#saveMessage'),'新版本已建立並發佈。')}catch(error){setMessage($('#saveMessage'),error.message,true)}}
async function removeVersion(){if(!currentId||!confirm(`確定刪除「${$('#versionName').value}」？此操作不能復原。`))return;setMessage($('#saveMessage'),'正在刪除…');try{const response=await fetch(endpoint(),{method:'DELETE',headers:{Authorization:`Bearer ${await token()}`}});if(!response.ok)throw new Error(`刪除失敗 (${response.status})`);currentId='';await reload();setMessage($('#saveMessage'),'版本已刪除，已返回預設版本。')}catch(error){setMessage($('#saveMessage'),error.message,true)}}
$('#loginButton').onclick=async()=>{setMessage($('#loginMessage'),'正在開啟 Google 登入…');try{await signInWithPopup(auth,provider)}catch(error){setMessage($('#loginMessage'),`登入失敗：${error.message}`,true)}};
$('#logout').onclick=()=>signOut(auth);$('#reload').onclick=reload;$('#editor').onsubmit=publish;
$('#versionSelect').onchange=async event=>{currentId=event.target.value;await reload()};$('#newVersion').onclick=()=>createVersion(false);$('#duplicateVersion').onclick=()=>createVersion(true);$('#deleteVersion').onclick=removeVersion;$('#copyVersionLink').onclick=async()=>{await navigator.clipboard.writeText(versionUrl());setMessage($('#saveMessage'),'前台網址已複製。')};
$('#addLevel').onclick=()=>{readForm();const n=config.levels.length+1;config.levels.push({name:`第${n}關`,image:'assets/level-1.svg',score:200,difficulty:'easy'});renderLevels()};
onAuthStateChanged(auth,async user=>{const allowed=user?.email?.toLowerCase()===ADMIN_EMAIL&&user.emailVerified;if(user&&!allowed){await signOut(auth);setMessage($('#loginMessage'),`此帳戶沒有管理權限：${user.email}`,true);return}$('#login').hidden=!!allowed;$('#editor').hidden=!allowed;$('#logout').hidden=!allowed;if(allowed){$('#userEmail').textContent=user.email;await reload()}});
